# sonar-project.properties
sonar.projectKey=sentiment-ai
sonar.projectName=SentimentAI
sonar.projectVersion=0.1.0
 
# Sources à analyser
sonar.sources=src
sonar.tests=tests
 
# Python
sonar.language=python
sonar.python.version=3.11
 
# Rapport de couverture généré par pytest-cov
sonar.python.coverage.reportPaths=coverage.xml
 
# Encodage
sonar.sourceEncoding=UTF-8
